name: nyumbani_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cloud_firestore: ^6.0.3
  collection: ^1.19.1
  email_otp: ^3.0.2
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.8
  flutter_otp_text_field: ^1.5.1+1
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.4
  intl: ^0.20.2
  paged_vertical_calendar: ^1.1.10
  path_provider: ^2.1.5
  phosphor_flutter: ^2.1.0
  rxdart: ^0.28.0
  sembast: ^3.8.5+1
  sembast_web: ^2.4.2
  shared_preferences: ^2.5.3
  table_calendar: ^3.2.0
  toastification: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/listing/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
